### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by forever2019** [azerothcore/mod-auto-revive#10] opened 2020-11-28 01:43 UTC
![QQ截图20201128094130](https://user-images.githubusercontent.com/49540243/100491400-17bed000-315e-11eb-96f3-8d854aacb41a.jpg)

**Comment by Helias** [comment] 2020-11-28 11:37
duplicate of https://github.com/azerothcore/mod-auto-revive/issues/6
try to test the module with the latest version because it can be already fixed, if so, write a comment in the issue https://github.com/azerothcore/mod-auto-revive/issues/6

**Closed by Helias** 2020-11-28 11:37 UTC
